version: "3.9"
services:
  wvp:
    image: hsw_wvp:1.3
    restart: always
    network_mode: host
    volumes:
      - ./logs/wvp:/opt/wvp/logs/
      - ./logs/assist:/opt/assist/logs/
      - ./docker_opt/wvp/config:/opt/wvp/config
      - ./docker_opt/assist/config:/opt/assist/config
      - /application_pool/wvp_zlmediakit/record:/opt/media/bin/www/record
    environment:
      ZLM_HOST: ${ZLM_HOST}
      ZLM_PORT: ${ZLM_PORT}
      ZLM_SECRET: ${ZLM_SECRET}
      ZLM_PORT_RANGE: ${ZLM_PORT_RANGE}
      ZLM_SEND_PORT_RANGE: ${ZLM_SEND_PORT_RANGE}
      TZ: ${TZ}
      WVP_IP: ${WVP_IP}
      WVP_HOST: ${WVP_HOST}
      WVP_PORT: ${WVP_PORT}
      WVP_HTTP_PORT: ${WVP_HTTP_PORT}
      WVP_ASSIST_PORT: ${WVP_ASSIST_PORT}
      WVP_PWD: ${WVP_PWD}
      WVP_DOMAIN: ${WVP_DOMAIN}
      WVP_ID: ${WVP_ID}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_DB: ${REDIS_DB}
      REDIS_PWD: ${REDIS_PWD}
      ASSIST_JVM_CONFIG_XMS: ${ASSIST_JVM_CONFIG_XMS}
      ASSIST_JVM_CONFIG_XMX: ${ASSIST_JVM_CONFIG_XMX}
      WVP_JVM_CONFIG_XMS: ${WVP_JVM_CONFIG_XMS}
      WVP_JVM_CONFIG_XMX: ${WVP_JVM_CONFIG_XMX}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      ASSIST_CONFIG:
      WVP_CONFIG:
    depends_on:
      - mysql
  mysql:
    image: mariadb:10.7.3 # 指定镜像和版本
    restart: always
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
        "--default-time-zone=+8:00",
      ]
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      SQL_MODE: "STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
    volumes:
      - /application_pool/wvp_mysql:/var/lib/mysql:rw # 挂载数据目录
    networks:
      - backend
  zlm:
    image: hkutangyu/zlmediakit:1.0
    ports:
      - ${ZLM_PORT}:${ZLM_PORT}
      - ${ZLM_RTMP_PORT}:${ZLM_RTMP_PORT}
      - ${ZLM_HTTPS_PORT}:443
      - ${ZLM_RTSP_PORT}:554
      - 10001:10001
      - ${ZLM_RTC_UDP}:${ZLM_RTC_UDP}
      - ${ZLM_SRT_UDP}:${ZLM_SRT_UDP}
      - ${ZLM_PORT_RANGE}:${ZLM_PORT_RANGE}
    restart: always
    networks:
      - backend
    volumes:
      - ./zlm_config:/opt/media/conf:rw # 挂载配置目录
      - /application_pool/wvp_zlmediakit/record:/opt/media/bin/www/record # 挂载录像目录
networks:
  backend:
  driver: bridge
  ipam:
    config:
      - subnet: 172.28.0.0/16
